### ISSUE TITLE
hspec/setup-haskell broken on macos-latest (macos-14)

### ISSUE THREAD

**Issue by andreasabel** [hspec/setup-haskell#44]
The macos-14 image does not have ghc in the path any longer:
https://github.com/sol/doctest/actions/runs/9172384682/job/25218779659?pr=423#step:3:7
> 
> Run hspec/setup-haskell@v1
>   with:
>     ghc-version: system
> Workaround for https://github.com/actions/runner-images/issues/7061
> Error: Unable to locate executable file: ghc. Please verify either the file path exists or the file can be found within a directory >specified by the PATH environment variable. Also check the file mode to verify the file is executable.

**Comment by sol** [comment]
Thanks @andreasabel.  For the time being, I'm not going to do anything here.  `macos-12` still works.
